In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
import seaborn as sns

In [ ]:
URL=pd.read_csv(r'/content/Two Machines.csv')

FileNotFoundError: ignored

In [ ]:
URL.describe()

In [ ]:
URL.head()

In [ ]:
URL.info()

In [ ]:
m1 = URL[URL['Machine'] == 'Machine 1']['Volume']
m2 = URL[URL['Machine'] == 'Machine 2']['Volume']

In [ ]:
m1

In [ ]:
from statsmodels.stats import weightstats 


In [ ]:
import scipy.stats as stats

In [ ]:
weightstats.ztest(m1, m2)

In [ ]:
stats.ttest_ind(m1, m2, equal_var=True)

In [ ]:
tips = sns.load_dataset("tips")

In [ ]:
tips.head()

In [ ]:
tips.describe()

In [ ]:
tm=tips[tips['sex']=='Male']['tip']

In [ ]:
tf=tips[tips['sex']=='Female']['tip']

In [ ]:
from statsmodels.stats import weightstats 
import scipy.stats as stats

Z TEST

In [ ]:
weightstats.ztest(tf, tm)

T TEST

In [ ]:
stats.ttest_ind(tf, tm, equal_var=True)

**CREATED** **LIST**

In [ ]:
m1 = [150, 151, 152, 152, 151, 150]
m2 = [153, 152, 148, 151, 149, 152]
m3 = [156, 154, 155, 156, 157, 155]

In [ ]:
from statsmodels.stats import oneway as oneway

F TEST

In [ ]:
stats.f_oneway(m1, m2, m3)

In [ ]:
mpg = sns.load_dataset("mpg")

In [ ]:
mpg

In [ ]:
mpg.groupby('origin').mean()['mpg']

**ANOVA**

In [ ]:
eu = mpg[(mpg['cylinders'] == 4) & (mpg['origin'] == 'europe')]['mpg']

In [ ]:
jp = mpg[(mpg['cylinders'] == 4) & (mpg['origin'] == 'europe')]['mpg']

In [ ]:
usa = mpg[(mpg['cylinders'] == 4) & (mpg['origin'] == 'europe')]['mpg']

In [ ]:
eu

In [ ]:
jp

In [ ]:
usa

F TEST

In [ ]:
import scipy.stats as stats

In [ ]:
stats.f_oneway(eu,jp,usa)

In [ ]:
url= r'https://img1.wsimg.com/blobby/go/8c96521b-7ee0-4579-b983-c9c9fac1057e/downloads/FuelEconomy.csv?ver=1609666327321'

In [ ]:
URL=pd.read_csv(url)

In [ ]:
URL.info()

In [ ]:
y= URL['Fuel Economy']

In [ ]:
y.shape

In [ ]:
X= URL[['Horsepower']]

In [ ]:
X.shape

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
regmodel = LinearRegression()

In [ ]:
regmodel.fit(X,y)

In [ ]:
regmodel.intercept_

In [ ]:
regmodel.coef_

In [ ]:
Fueleconomy= 39.23-0.072hp


In [ ]:
#practice

In [ ]:
url= r'https://img1.wsimg.com/blobby/go/8c96521b-7ee0-4579-b983-c9c9fac1057e/downloads/FuelEconomy.csv?ver=1609666327321'

In [ ]:
URL=pd.read_csv(url)

In [ ]:
URL.head()

In [ ]:
URL.describe()

In [ ]:
URL.info()

In [ ]:
X=URL[["Horsepower"]]

In [ ]:
X.shape

(100, 1)

In [ ]:
y=URL["Fuel Economy"]

In [ ]:
y.shape

(100,)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state=123)

In [ ]:
X_train

Horsepower
21         233
90         238
33         283
69         316
84         225
..         ...
57         285
83         233
17         192
92         228
66         246

[70 rows x 1 columns]

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
model = LinearRegression()

In [ ]:
model

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
model.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
model.intercept_

39.21799410042862

In [ ]:
model.coef_

array([-0.0725134])

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
y_pred

array([30.00879172, 22.97499148, 23.48258531, 32.54676088, 23.77263893,
       30.58889896, 26.4556349 , 28.26847001, 21.08964296, 23.3375585 ,
       28.99360406, 26.02055447, 23.62761212, 22.46739765, 21.52472339,
       21.52472339, 15.94119124, 28.1234432 , 20.94461615, 23.19253169,
       17.31894592, 24.42525957, 29.28365768, 30.51638555, 26.4556349 ,
       24.28023276, 21.88729041, 27.32579575, 21.01712956, 26.67317511])

In [ ]:
y_pred.shape

(30,)

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [ ]:
mean_absolute_error(y_test, y_pred)

1.0162497749316688

#Problem 2

In [ ]:
Url=r"https://img1.wsimg.com/blobby/go/8c96521b-7ee0-4579-b983-c9c9fac1057e/downloads/SAT%20GPA.csv?ver=1610864531937"

In [ ]:
import pandas as pd

In [ ]:
df1=pd.read_csv(Url)

In [ ]:
df1.head()

SAT  GPA
0  1270  3.4
1  1220  4.0
2  1160  3.8
3   950  3.8
4  1070  4.0

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   SAT     1000 non-null   int64  
 1   GPA     1000 non-null   float64
dtypes: float64(1), int64(1)
memory usage: 15.8 KB


In [ ]:
df1.describe()

SAT          GPA
count  1000.000000  1000.000000
mean   1033.290000     3.203700
std     142.873681     0.542541
min     530.000000     1.800000
25%     930.000000     2.800000
50%    1030.000000     3.200000
75%    1130.000000     3.700000
max    1440.000000     4.500000

In [ ]:
X=df1[["SAT"]]

In [ ]:
X.shape

(1000, 1)

In [ ]:
y=df1["GPA"]

In [ ]:
y.shape

(1000,)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.7, random_state = 123)

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
lr=LinearRegression()

In [ ]:
lr.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
lr.coef_

array([0.00163826])

In [ ]:
lr.intercept_

1.5240905555052968

In [ ]:
#GPA=1.52+0.0016SAT+error

In [ ]:
y_pred=lr.predict(X_test)

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [ ]:
mean_squared_error(y_test,y_pred)

0.2335021086958436

In [ ]:
mean_absolute_error(y_test,y_pred)

0.39522269161675877